swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts
      summary: User Accounts API
      description: API for fetching user's accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User's accounts retrieved successfully
          schema:
            $ref: '#/definitions/AccountsResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Accounts for User Not Found
        '500':
          description: Internal Server Error
  /user/accounts/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts
      summary: User Account API
      description: API for fetching specified user account informations
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          type: string
          description: Account identifier
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User account information retrievied successfully
          schema:
            $ref: '#/definitions/Account'
        '400':
          description: Invalid Fields
        '404':
          description: Account for User Not Found
        '500':
          description: Internal Server Error
  /user/accounts/{id}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: User Account Transactions API
      description: API for fetching account's transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          type: string
          description: Account identifier
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions for specified account retrievied successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Transactions for Account Not Found
        '500':
          description: Internal Server Error
  /user/accounts/{id}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: User Account Transaction API
      description: API for fetching specified account transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          type: string
          description: Account identifier
          required: true
        - in: path
          name: transactionId
          type: string
          description: Transaction identifier
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details for specified account retrievied successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction for Account Not Found
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: User Account Transaction API
      description: API to update a specified transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          type: string
          description: Account identifier
          required: true
        - in: path
          name: transactionId
          type: string
          description: Transaction identifier
          required: true
        - in: body
          name: body
          description: Updated transaction information
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction successfully updated
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction for Account Not Found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  AccountsResponse:
    properties:
      accounts:
        type: array
        description: List of user accounts
        items:
          $ref: '#/definitions/Account'
  Account:
    properties:
      id:
        type: string
        description: Identifier of account
      name:
        type: string
        description: Name of account
      balance:
        type: number
        description: Balance of account
      transactions:
        type: array
        description: List of user account transactions
        items:
          $ref: '#/definitions/Transaction'
  TransactionsResponse:
    properties:
      transactions:
        type: array
        description: List of transactions for user account
        items:
          $ref: '#/definitions/Transaction'
  Transaction:
    properties:
      id:
        type: string
        description: Identifier for transaction
      date:
        type: string
        description: Date of transaction
        format: date
      description:
        type: string
        description: Description of transaction
      amount:
        type: number
        description: Amount of transaction
      accountBalance:
        type: number
        description: Balance of account after transaction
